# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: infostack
google_analytics: UA-62411796-1
fb_app_id: 753888716014248
title: Info Stack

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Info Stack

description: Rohan Jaswal's blog
author:
  name: Rohan Jaswal
  email: rohanjaswal2507@gmail.com
  github: rohanjaswal2507
  twitter: rohanjaswal2507
  linkedin: rohanjaswal2507
  bio: Software Engineer at Udemy. Playing around with Python, Java and stuff!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
other_publication_path: other-posts.html
books: books/index.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

timezone: Asia/Kolkata

BASE_PATH:

plugins:
  - jekyll-paginate
